- Camera Config:
    Camera Name: Logitech C270
    Field of View: 55
    Focal Length: 30
    Sensor Height: null
  Yolo CFG: D:\Desktop\DepthEstimator\data\Yolo.cfg
  Yolo Labels: D:\Desktop\DepthEstimator\data\coco.names
  Yolo Weights: D:\Desktop\DepthEstimator\models\Yolo.weights
  model: model-f6b98070.onnx
  model path: D:\Desktop\DepthEstimator\models
